package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "galerieart09")
public class Adresse implements java.io.Serializable {

	private Integer idAdresse;
	private Pays pays;
	private String rue;
	private String numero;
	private String localite;
	private String codePostal;
	private Localexpo localexpo; // Cet attribut n'est utilisé que pour la relation One to One
	private Set<Artiste> artistes = new HashSet<Artiste>(0);
	private Set<Client> clients = new HashSet<Client>(0);

	public Adresse() {
	}

	public Adresse(Pays pays, String rue, String numero, String localite,
			String codePostal) {
		this.pays = pays;
		this.rue = rue;
		this.numero = numero;
		this.localite = localite;
		this.codePostal = codePostal;
	}

	public Adresse(Pays pays, String rue, String numero, String localite,
			String codePostal, Localexpo localexpo, Set<Artiste> artistes,
			Set<Client> clients) {
		this.pays = pays;
		this.rue = rue;
		this.numero = numero;
		this.localite = localite;
		this.codePostal = codePostal;
		this.localexpo = localexpo;
		this.artistes = artistes;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAdresse", unique = true, nullable = false)
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPays", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@Column(name = "rue", nullable = false, length = 100)
	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name = "numero", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "localite", nullable = false, length = 100)
	public String getLocalite() {
		return this.localite;
	}

	public void setLocalite(String localite) {
		this.localite = localite;
	}

	@Column(name = "codePostal", nullable = false, length = 100)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Localexpo getLocalexpo() {
		return this.localexpo;
	}

	public void setLocalexpo(Localexpo localexpo) {
		this.localexpo = localexpo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Artiste> getArtistes() {
		return this.artistes;
	}

	public void setArtistes(Set<Artiste> artistes) {
		this.artistes = artistes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@Override
	public String toString() {
		return "Adresse [idAdresse=" + idAdresse + ", pays=" + pays + ", rue="
				+ rue + ", numero=" + numero + ", localite=" + localite
				+ ", codePostal=" + codePostal + ", localexpo=" + localexpo
				+ "]";
	}




	
	
	
	
}
