package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Artiste generated by hbm2java
 */
@Entity
@Table(name = "artiste", catalog = "galerieart09")
public class Artiste implements java.io.Serializable {
	
	private Integer idArtiste;
	private Adresse adresse;
	private String nom;
	private String prenom;
	private String email;
	private String telephone;
	private Set<Oeuvre> oeuvres = new HashSet<Oeuvre>(0);

	public Artiste() {
	}

	public Artiste(Adresse adresse, String nom, String prenom, String email,
			String telephone) {
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.telephone = telephone;
	}

	public Artiste(Adresse adresse, String nom, String prenom, String email,
			String telephone, Set<Oeuvre> oeuvres) {
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.telephone = telephone;
		this.oeuvres = oeuvres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idArtiste", unique = true, nullable = false)
	public Integer getIdArtiste() {
		return this.idArtiste;
	}

	public void setIdArtiste(Integer idArtiste) {
		this.idArtiste = idArtiste;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAdresse", nullable = false)
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", nullable = false, length = 100)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artiste")
	public Set<Oeuvre> getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set<Oeuvre> oeuvres) {
		this.oeuvres = oeuvres;
	}

	@Override
	public String toString() {
		return "" + nom + "    " + prenom ;
	}

	/*
	@Override
	public String toString() {
		return "Artiste [idArtiste=" + idArtiste + ", adresse=" + adresse
				+ ", nom=" + nom + ", prenom=" + prenom + ", email=" + email
				+ ", telephone=" + telephone + "]";
	}
	*/
	
	
	
	
}
