package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "galerieart09")
public class Client implements java.io.Serializable {

	private Integer idClient;
	private Adresse adresse;
	private String nom;
	private String prenom;
	private String email;
	private Date dateClient;
	private byte accordNewsletter;
	private Set<Reception> receptions = new HashSet<Reception>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);
	private Set<Participation> participations = new HashSet<Participation>(0);

	public Client() {
	}

	public Client(Adresse adresse, String nom, String prenom, String email,
			Date dateClient, byte accordNewsletter) {
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.dateClient = dateClient;
		this.accordNewsletter = accordNewsletter;
	}

	public Client(Adresse adresse, String nom, String prenom, String email,
			Date dateClient,byte accordNewsletter, Set<Reception> receptions,
			Set<Facture> factures, Set<Participation> participations) {
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.dateClient = dateClient;
		this.accordNewsletter = accordNewsletter;
		this.receptions = receptions;
		this.factures = factures;
		this.participations = participations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idClient", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAdresse", nullable = false)
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateClient", nullable = false, length = 10)
	public Date getDateClient() {
		return this.dateClient;
	}

	public void setDateClient(Date dateClient) {
		this.dateClient = dateClient;
	}

	
	@Column(name = "accordNewsletter", nullable = false, length = 4)
	public byte getAccordNewsletter() {
		return accordNewsletter;
	}

	public void setAccordNewsletter(byte accordNewsletter) {
		this.accordNewsletter = accordNewsletter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Reception> getReceptions() {
		return this.receptions;
	}

	public void setReceptions(Set<Reception> receptions) {
		this.receptions = receptions;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Participation> getParticipations() {
		return this.participations;
	}

	public void setParticipations(Set<Participation> participations) {
		this.participations = participations;
	}

	@Override
	public String toString() {
		return "Client [idClient=" + idClient + ", adresse=" + adresse
				+ ", nom=" + nom + ", prenom=" + prenom + ", email=" + email
				+ ", dateClient=" + dateClient + ", accordNewsletter="
				+ accordNewsletter + "]";
	}

	

	
	
	

	
	
	
}
