package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Courant generated by hbm2java
 */
@Entity
@Table(name = "courant", catalog = "galerieart09")
public class Courant implements java.io.Serializable {

	private Integer idCourant;
	private String nomCourant;
	private Set<Oeuvre> oeuvres = new HashSet<Oeuvre>(0);

	public Courant() {
	}

	public Courant(String nomCourant) {
		this.nomCourant = nomCourant;
	}

	public Courant(String nomCourant, Set<Oeuvre> oeuvres) {
		this.nomCourant = nomCourant;
		this.oeuvres = oeuvres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCourant", unique = true, nullable = false)
	public Integer getIdCourant() {
		return this.idCourant;
	}

	public void setIdCourant(Integer idCourant) {
		this.idCourant = idCourant;
	}

	@Column(name = "nomCourant", nullable = false, length = 100)
	public String getNomCourant() {
		return this.nomCourant;
	}

	public void setNomCourant(String nomCourant) {
		this.nomCourant = nomCourant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courant")
	public Set<Oeuvre> getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set<Oeuvre> oeuvres) {
		this.oeuvres = oeuvres;
	}

	@Override
	public String toString() {
		return "Courant [idCourant=" + idCourant + ", nomCourant=" + nomCourant
				+ "]";
	}

	
	
	
	
}
