package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Horaire generated by hbm2java
 */
@Entity
@Table(name = "horaire", catalog = "galerieart09")
public class Horaire implements java.io.Serializable {

	
	private Integer idHoraire;
	private Localexpo localexpo;
	private String jour;
	private String heureOuverture;
	private String heureFermeture;
	

	public Horaire() {
	}

	public Horaire(String jour, String heureOuverture, String heureFermeture, 
															Localexpo localexpo) {
		this.jour = jour;
		this.heureOuverture = heureOuverture;
		this.heureFermeture = heureFermeture;
		this.localexpo=localexpo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idHoraire", unique = true, nullable = false)
	public Integer getIdHoraire() {
		return this.idHoraire;
	}

	public void setIdHoraire(Integer idHoraire) {
		this.idHoraire = idHoraire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAdresseLocal", nullable = false)
	public Localexpo getLocalexpo() {
		return this.localexpo;
	}

	public void setLocalexpo(Localexpo localexpo) {
		this.localexpo = localexpo;
	}

	
	@Column(name = "jour", nullable = false, length = 50)
	public String getJour() {
		return this.jour;
	}

	public void setJour(String jour) {
		this.jour = jour;
	}

	@Column(name = "HeureOuverture", nullable = false, length = 100)
	public String getHeureOuverture() {
		return this.heureOuverture;
	}

	public void setHeureOuverture(String heureOuverture) {
		this.heureOuverture = heureOuverture;
	}

	@Column(name = "HeureFermeture", nullable = false, length = 100)
	public String getHeureFermeture() {
		return this.heureFermeture;
	}

	public void setHeureFermeture(String heureFermeture) {
		this.heureFermeture = heureFermeture;
	}

	
	@Override
	public String toString() {
		return "Horaire [idHoraire=" + idHoraire + ", jour=" + jour
				+ ", heureOuverture=" + heureOuverture + ", heureFermeture="
				+ heureFermeture + "]";
	}


	
	
	
}
