package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Newsletter generated by hbm2java
 */
@Entity
@Table(name = "newsletter", catalog = "galerieart09")
public class Newsletter implements java.io.Serializable {

	private Integer idNewsletter;
	private String contenu;
	private String sujet;
	private Date dateEnvoi;
	private Set<Reception> receptions = new HashSet<Reception>(0);

	public Newsletter() {
	}

	public Newsletter(String contenu, String sujet,
			Date dateEnvoi) {
		this.contenu = contenu;
		this.dateEnvoi = dateEnvoi;
		this.sujet = sujet;
	}

	public Newsletter(String contenu, String sujet,
			Date dateEnvoi, Set<Reception> receptions) {
		this.contenu = contenu;
		this.dateEnvoi = dateEnvoi;
		this.receptions = receptions;
		this.sujet = sujet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idNewsletter", unique = true, nullable = false)
	public Integer getIdNewsletter() {
		return this.idNewsletter;
	}

	public void setIdNewsletter(Integer idNewsletter) {
		this.idNewsletter = idNewsletter;
	}

	
	@Column(name = "contenu", nullable = false, length = 65535)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateEnvoi", nullable = false, length = 10)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "newsletter")
	public Set<Reception> getReceptions() {
		return this.receptions;
	}

	public void setReceptions(Set<Reception> receptions) {
		this.receptions = receptions;
	}
	
	@Column(name = "sujet", nullable = false, length = 100)
	public String getSujet() {
		return sujet;
	}

	public void setSujet(String sujet) {
		this.sujet = sujet;
	}

	@Override
	public String toString() {
		return "Newsletter [idNewsletter=" + idNewsletter + ", contenu="
				+ contenu + ", sujet=" + sujet + ", dateEnvoi=" + dateEnvoi
				+ "]";
	}

	
	
	
	
	
}
