package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays", catalog = "galerieart09")
public class Pays implements java.io.Serializable {

	private Integer idPays;
	private String nom;
	private Set<Adresse> adresses = new HashSet<Adresse>(0);

	public Pays() {
	}

	public Pays(String nom) {
		this.nom = nom;
	}

	public Pays(String nom, Set<Adresse> adresses) {
		this.nom = nom;
		this.adresses = adresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPays", unique = true, nullable = false)
	public Integer getIdPays() {
		return this.idPays;
	}

	public void setIdPays(Integer idPays) {
		this.idPays = idPays;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	public Set<Adresse> getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set<Adresse> adresses) {
		this.adresses = adresses;
	}

	@Override
	public String toString() {
		return "Pays [idPays=" + idPays + ", nom=" + nom + "]";
	}

	
	
	
	
}
