package pojo;

// Generated 13 avr. 2014 16:46:50 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Technique generated by hbm2java
 */
@Entity
@Table(name = "technique", catalog = "galerieart09")
public class Technique implements java.io.Serializable {

	private Integer idTechnique;
	private String nomTechnique;
	private Set<Oeuvre> oeuvres = new HashSet<Oeuvre>(0);

	public Technique() {
	}

	public Technique(String nomTechnique) {
		this.nomTechnique = nomTechnique;
	}

	public Technique(String nomTechnique, Set<Oeuvre> oeuvres) {
		this.nomTechnique = nomTechnique;
		this.oeuvres = oeuvres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTechnique", unique = true, nullable = false)
	public Integer getIdTechnique() {
		return this.idTechnique;
	}

	public void setIdTechnique(Integer idTechnique) {
		this.idTechnique = idTechnique;
	}

	@Column(name = "nomTechnique", nullable = false, length = 100)
	public String getNomTechnique() {
		return this.nomTechnique;
	}

	public void setNomTechnique(String nomTechnique) {
		this.nomTechnique = nomTechnique;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "technique")
	public Set<Oeuvre> getOeuvres() {
		return this.oeuvres;
	}

	public void setOeuvres(Set<Oeuvre> oeuvres) {
		this.oeuvres = oeuvres;
	}

	@Override
	public String toString() {
		return "Technique [idTechnique=" + idTechnique + ", nomTechnique="
				+ nomTechnique + "]";
	}

}
